# Generated by Django 6.0.6 on 2026-07-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('runningtime', models.IntegerField()),
                ('reviews', models.TextField()),
            ],
        ),
    ]
