# Generated by Django 6.0.6 on 2026-07-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
