# Generated by Django 6.0.6 on 2026-07-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0003_remove_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='reviews',
            new_name='review_text',
        ),
    ]
