# Generated by Django 6.0.6 on 2026-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideastar',
            name='user',
        ),
        migrations.AddField(
            model_name='ideastar',
            name='session_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='ideastar',
            constraint=models.UniqueConstraint(fields=('session_key', 'idea'), name='unique_session_idea_star'),
        ),
    ]
